language: generic
dist: xenial

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://$MASTER_NODE:2376"
    - DOCKER_CERT_PATH="$TRAVIS_BUILD_DIR/.certs"

before_script:
  - openssl aes-256-cbc -K $encrypted_235106e876e9_key -iv $encrypted_235106e876e9_iv -in certs.tar.enc -out certs.tar -d
  - mkdir $DOCKER_CERT_PATH
  - tar xvf certs.tar -C $DOCKER_CERT_PATH


script:
  - bash ./deploy.sh