version: '3.7'

services:
  web:
    image: ghost:2.31-alpine
    volumes:
      - ghost:/var/lib/ghost/content:nocopy
    environment:
      url: https://${DOMAIN_GHOST:?err}
      mail__transport: SMTP
      mail__options__service: MAILGUN
      mail__options__host: "smtp.eu.mailgun.org"
      mail__options__port: 465
      mail__options__secureConnection: "true"
      mail__options__auth__user: ${MAILGUN_USER:?err}
      mail__options__auth__pass: ${MAILGUN_PASSWORD:?err}
      mail__from: ${MAIL_FROM_GHOST:-'Example Blog' <noreply@blog.example.com>}

    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.ghost.entrypoints: http
        traefik.http.routers.ghost.rule: Host(`${DOMAIN_GHOST:?err}`)
        traefik.http.routers.ghost.middlewares: redirect-https
        traefik.http.routers.ghost-secure.entrypoints: https
        traefik.http.routers.ghost-secure.rule: Host(`${DOMAIN_GHOST:?err}`)
        traefik.http.routers.ghost-secure.tls.certresolver: letsencrypt
        traefik.http.services.ghost-service.loadbalancer.server.port: "2368"
    networks:
      - external
      - internal

volumes:
  ghost:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/blog/ghost

networks:
  external:
    name: traefik-net
    external: true
  internal: