version: '3.7'

services:
  web:
    image: ghost:2.31-alpine
    volumes:
      - ghost:/var/lib/ghost/content:nocopy
    environment:
      url: https://${DOMAIN_GHOST:?err}
    deploy:
      labels:
        traefik.http.routers.ghost.entrypoints: https
        traefik.http.routers.ghost.rule: Host(`${DOMAIN_GHOST:?err}`)
        traefik.http.routers.ghost.tls.certresolver: letsencrypt
        traefik.http.services.ghost-service.loadbalancer.server.port: "2368"
        traefik.enable: "true"

volumes:
  ghost:

networks:
  default:
    name: traefik-net
    external: true