version: '3.7'

x-blog: &blog-app
  image: ghost:4.48.6-alpine
  environment:
    url: https://${DOMAIN_GHOST:?err}
    mail__transport: SMTP
    mail__options__service: MAILGUN
    mail__options__host: "smtp.eu.mailgun.org"
    mail__options__port: 465
    mail__options__secureConnection: "true"
    mail__options__auth__user: ${MAILGUN_USER:?err}
    mail__options__auth__pass: ${MAILGUN_PASSWORD:?err}
    mail__from: ${MAIL_FROM_GHOST:-'Example Blog' <noreply@blog.example.com>}

services:
  db:
    image: mariadb:10.6
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - internal
  web_v5:
    image: ghost:5
    environment:
      url: https://blog.julescheron.com
      mail__transport: SMTP
      mail__options__service: MAILGUN
      mail__options__host: "smtp.eu.mailgun.org"
      mail__options__port: 465
      mail__options__secureConnection: "true"
      mail__options__auth__user: ${MAILGUN_USER:?err}
      mail__options__auth__pass: ${MAILGUN_PASSWORD:?err}
      mail__from: ${MAIL_FROM_GHOST:-'Example Blog' <noreply@blog.example.com>}
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ${BLOG_DB_PASSWORD}
      database__pool__min: 2
      database__pool__max: 10
      database__connection__database: blog
      database__pool__ping: function (conn, cb) { conn.query('SELECT 1', cb); }  }
    volumes:
      - ghostv5:/var/lib/ghost/content:nocopy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.ghostv5.entrypoints: https
        traefik.http.routers.ghostv5.rule: Host(`blog.julescheron.com`)
        traefik.http.routers.ghostv5.tls.certresolver: letsencrypt
        traefik.http.services.ghostv5-service.loadbalancer.server.port: "2368"
    networks:
      - internal
      - external

  web:
    <<: *blog-app 
    volumes:
      - ghost:/var/lib/ghost/content:nocopy
    deploy:
      labels:
        traefik.enable: "false"
        traefik.http.routers.ghost.entrypoints: https
        traefik.http.routers.ghost.rule: Host(`${DOMAIN_GHOST:?err}`)
        traefik.http.routers.ghost.tls.certresolver: letsencrypt
        traefik.http.services.ghost-service.loadbalancer.server.port: "2368"
    networks:
      - external
  web-fr:
    <<: *blog-app 
    volumes:
      - ghost-fr:/var/lib/ghost/content:nocopy
    environment:
      url: https://${DOMAIN_GHOST:?err}/fr/
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.ghost-fr.entrypoints: https
        traefik.http.routers.ghost-fr.rule: Host(`${DOMAIN_GHOST:?err}`) && PathPrefix(`/fr`)
        traefik.http.routers.ghost-fr.tls.certresolver: letsencrypt
        traefik.http.services.ghost-fr-service.loadbalancer.server.port: "2368"
    networks:
      - external

volumes:
  ghost:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/blog/ghost
  ghostv5:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/blog/ghostv5
  ghost-fr:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/blog/ghost-fr
  db:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/blog/db
networks:
  external:
    name: traefik-net
    external: true
  internal:
