version: '3.7'

services:
  server:
    image: registry.gitlab.com/commento/commento:v1.7.0
    ports:
      - 8090:8090
    environment:
      COMMENTO_ORIGIN: https://${DOMAIN_COMMENTO:?err}
      COMMENTO_PORT: 8090
      COMMENTO_POSTGRES: postgres://commento:commento@db:5432/commento?sslmode=disable
      COMMENTO_FORBID_NEW_OWNERS: "true"
      COMMENTO_SMTP_HOST: "smtp.eu.mailgun.org"
      COMMENTO_SMTP_PORT: 587
      COMMENTO_SMTP_USERNAME: ${MAILGUN_USER:?err}
      COMMENTO_SMTP_PASSWORD: ${MAILGUN_PASSWORD:?err}
      COMMENTO_SMTP_FROM_ADDRESS: ${MAIL_FROM_COMMENTO:-'Example Blog' <noreply@commento.example.com>}

    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.commento.entrypoints: https
        traefik.http.routers.commento.rule: Host(`${DOMAIN_COMMENTO:?err}`)
        traefik.http.routers.commento.tls.certresolver: letsencrypt
        traefik.http.services.commento-service.loadbalancer.server.port: "8090"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: commento
      POSTGRES_PASSWORD: commento
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

volumes:
  postgres_data_volume:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/commento/db

networks:
  default:
    name: traefik-net
    external: true
