version: "3"

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
    networks:
      - internal

  app:
    image: matomo:fpm-alpine
    restart: always
    volumes:
      # - ./config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - MATOMO_DATABASE_DBNAME=matomo
    networks:
      - internal

  web:
    image: nginx:alpine
    restart: always
    configs:
      - source: matomo.conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
    networks:
      - internal
      - external
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.matomo.entrypoints: https
        traefik.http.routers.matomo.rule: Host(`matomo.julescheron.com`)
        traefik.http.routers.matomo.tls.certresolver: letsencrypt
        traefik.http.services.matomo-service.loadbalancer.server.port: "80"

volumes:
  db:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/matomo/db
  matomo:

networks:
  external:
    name: traefik-net
    external: true
  internal:

configs:
  matomo.conf:
    file: ./config/matomo.conf
    name: matomo.conf-${CONFIG_VERSION:-0}