version: "3.7"

services:
  proxy:
    image: traefik:2.0
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt
    deploy:
      placement:
        constraints: [node.role==manager]
      labels:
        traefik.http.routers.api.rule: Host(`${DOMAIN_TRAEFIK:?err}`)
        traefik.http.routers.api.service: api@internal
        traefik.http.routers.api.middlewares: ipwhitelist
        traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange: ${IP_WHITELIST:?err}, 127.0.0.1
    configs:
      - source: traefik.toml
        target: /traefik.toml
configs:
  traefik.toml:
    file: ./config/traefik.toml
    name: traefik.toml-${CONFIG_VERSION:-0}

volumes:
  certs:

networks:
  default:
    name: traefik-net
    driver: overlay
    attachable: true