version: "3.7"

services:
  proxy:
    image: traefik:2.0
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt
    deploy:
      placement:
        constraints: [node.role==manager]
    configs:
      - source: config
        target: /traefik.toml
configs:
  config:
    file: ./config/traefik.toml

volumes:
  certs:

networks:
  default:
    name: traefik-net
    driver: overlay
    attachable: true