version: '3.7'

services:
    server:
      image: remie/youtransfer:stable
      deploy:
        labels:
          traefik.enable: "true"
          traefik.http.routers.youtransfer.entrypoints: https
          traefik.http.routers.youtransfer.tls.certresolver: letsencrypt
          traefik.http.routers.youtransfer.rule: Host(`${DOMAIN_YOUTRANSFER:?err}`)
          traefik.http.services.youtransfer.loadbalancer.server.port: "5000"
      networks:
        - internal
        - external
      volumes:
        - config:/opt/youtransfer/config
        - uploads:/opt/youtransfer/uploads

volumes:
  uploads:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/youtransfer/uploads
  config:
    driver_opts:
      type: nfs
      o: "addr=${NFS_SERVER:?err},nfsvers=4,nolock,soft,rw"
      device: :/mnt/data/youtransfer/config

networks:
  external:
    name: traefik-net
    external: true
  internal: