debug = false
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"


[providers.docker]
  swarmmode = true
  exposedByDefault = false
  network = "traefik-net"
  endpoint = "tcp://dockerproxy:2375"

# Enable ACME (Let's Encrypt): automatic SSL.
[certificatesResolvers.letsencrypt.acme]

  email = "me@julescheron.com"
  # certificates storage.
  storage = "/letsencrypt/acme.json"
  keyType = "RSA4096"

  # Use a TLS-ALPN-01 ACME challenge.
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]

[api]
  dashboard = true